// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: entries.sql

package db

import (
	"context"
)

const createEntry = `-- name: CreateEntry :one
INSERT INTO entries (website_url, username, encryped_password)
VALUES (?, ?, ?)
RETURNING id, website_url, username, encryped_password, created_at
`

type CreateEntryParams struct {
	WebsiteUrl       string
	Username         string
	EncrypedPassword []byte
}

func (q *Queries) CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error) {
	row := q.db.QueryRowContext(ctx, createEntry, arg.WebsiteUrl, arg.Username, arg.EncrypedPassword)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.WebsiteUrl,
		&i.Username,
		&i.EncrypedPassword,
		&i.CreatedAt,
	)
	return i, err
}

const getEntry = `-- name: GetEntry :one
SELECT id, website_url, username, encryped_password, created_at FROM entries
WHERE website_url = ? AND username = ?
`

type GetEntryParams struct {
	WebsiteUrl string
	Username   string
}

func (q *Queries) GetEntry(ctx context.Context, arg GetEntryParams) (Entry, error) {
	row := q.db.QueryRowContext(ctx, getEntry, arg.WebsiteUrl, arg.Username)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.WebsiteUrl,
		&i.Username,
		&i.EncrypedPassword,
		&i.CreatedAt,
	)
	return i, err
}

const listEntries = `-- name: ListEntries :many
SELECT id, website_url, username FROM entries
ORDER BY website_url
`

type ListEntriesRow struct {
	ID         int64
	WebsiteUrl string
	Username   string
}

func (q *Queries) ListEntries(ctx context.Context) ([]ListEntriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listEntries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEntriesRow
	for rows.Next() {
		var i ListEntriesRow
		if err := rows.Scan(&i.ID, &i.WebsiteUrl, &i.Username); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
