// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type Config struct {
	Key   string
	Value []byte
}

type Entry struct {
	ID                int64
	WebsiteUrl        string
	Username          string
	EncryptedPassword []byte
	CreatedAt         sql.NullTime
}
